### PR TITLE
[Feat] Add Download Toast

### PR DESCRIPTION
**Pull request by BrettCleary**
## Summary
- Adds download toast
- Progresses UI design system overhaul
- Metrics for download toast click events
- Points submodules to latest main commits (this was not done after hardware wallet PR merge)
- Replaces frontend helper `handleStopInstallation` with react component `StopInstallationModal` 

### Tested
Tested download, cancel, and play game from finished expanded download toast for:
- [X] HyperPlay Downloads 
- [x] Legendary Downloads
- [x] Gog Downloads

#### Download Toast Collapsed
image
#### Download In Progress- Expanded Toast
image
#### Download Finished - Expanded Toast
image

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Testing this one here, I found a bug on the downloader screen that could be solved with some adjusting on the Z-index of the card:

image

**Comment by flavioislima** [comment]
Noticed some broken layout not sure if it is started on this Pr though, but I am pasting here so we can fix it later:
image

image

**Comment by BrettCleary** [comment]
@flavioislima 
1. zindex issue is fixed
2. manage accounts has text align center again now
3. epic alternative login modal is centered correctly now with the background blur across the full page
4. button default color is back to color-neutral-100
5. Zoom label is now above the zoom slider

### screenshots
1. image
image

2. image
3. image
4. image
5. image

**Comment by flavioislima** [comment]
I think the Play button is not correct as well, it does not have any background:

image

this modal to report a problem as well, I think the headers are a bit huge and the log is too narrow:

image

The other issues seems to be fixed 👍🏽

**Comment by BrettCleary** [comment]
@flavioislima 

updated game page cta to the new button component:
image
image
image

updated log modal log width and types (designers probably still need to recommend types here): 
image

**Comment by flavioislima** [comment]
Most of the issues were fixed, I think that the only thing that needs to be fixed now is the size of the developer name on the game page.

Also, add some small animations on the hover for the buttons, for the opacity change I mean. :)

**Comment by BrettCleary** [comment]
> Most of the issues were fixed, I think that the only thing that needs to be fixed now is the size of the developer name on the game page.
> 
> Also, add some small animations on the hover for the buttons, for the opacity change I mean. :)

okay latest commit addresses these issues

**Pull request merged**
