### PR TITLE
[Tech] Initialize HyperPlay with the previously selected wallet

### PR DESCRIPTION
**Pull request by hellowodl**
When the application starts, this PR will prevent HyperPlay from displaying the onboarding screen again by selecting the previously selected wallet.
Currently only implemented for the MetaMask extension

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by hellowodl** [comment]
> Codewise looks good but you need to fix the workflows that are failing 👍🏽

fixed :)

**Comment by flavioislima** [comment]
> > Codewise looks good but you need to fix the workflows that are failing 👍🏽
> 
> fixed :)

I think you still have a linting issue 😅

**Comment by hellowodl** [comment]
> > > Codewise looks good but you need to fix the workflows that are failing 👍🏽
> > 
> > 
> > fixed :)
> 
> I think you still have a linting issue sweat_smile

@flavioislima fixed

**Comment by BrettCleary** [comment]
Just tested again after merging the submodules.

All working:
- connecting with extension wallet and restarting app
- import wallet
- create new wallet

**Review by BrettCleary — APPROVED** [review]

**Pull request merged**
