### PR TITLE
[UI] Make Download Toast Draggable

### PR DESCRIPTION
**Pull request by flavioislima**
Change the behaviour of the `DownloadToastManager` to be draggable across the screen so it won't be on top of any other element.

Recordings:
Linux:
https://github.com/user-attachments/assets/c647834e-6c5b-4f71-b945-7b046d9f9fe7

macOS:
https://github.com/user-attachments/assets/79559724-bada-4296-aef3-2ea86c06a908

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by jiyuu-jin — APPROVED** [review]
Code LGTM, cool low hanging fruit, adds some nice functionality by just adding the draggable component.

**Review by eliobricenov — APPROVED** [review]

**Comment by flavioislima** [comment]
> Code LGTM, cool low hanging fruit, adds some nice functionality by just adding the draggable component.

yes, this library is a beast. Pretty simple to use it anywhere in the code.

**Review by BrettCleary — APPROVED** [review]
Nice and simple! It works, but is there a reason why it doesn't follow the mouse cursor the same distance?

When I click to drag it to the top left, the element only moves ~0.6 pixels for every pixel my mouse cursor moves, which feels a little janky

**Comment by flavioislima** [comment]
> Nice and simple! It works, but is there a reason why it doesn't follow the mouse cursor the same distance?
> 
> When I click to drag it to the top left, the element only moves ~0.6 pixels for every pixel my mouse cursor moves, which feels a little janky

Can you send a video?
I am using the defaults for this element, perhaps we can do some adjustments by passing some props to it.

**Comment by BrettCleary** [comment]
> > Nice and simple! It works, but is there a reason why it doesn't follow the mouse cursor the same distance?
> > When I click to drag it to the top left, the element only moves ~0.6 pixels for every pixel my mouse cursor moves, which feels a little janky
> 
> For me its is working fine as showing in the videos above. Can you send a screen recording? I am using the defaults for this element, perhaps we can do some adjustments by passing some props to it.

after some more investigation, this only happens with the devtools console open. with it closed, it works as expected 👌

**Review by nyghtstalker — APPROVED** [review]
I love it! Super fun and cool! You can drag it to any page/screen and minimize it! Well done!

image
image

**Pull request merged**
