### PR TITLE
[FIX] Check isAvailable when using TargetEXE Setting

### PR DESCRIPTION
**Pull request by flavioislima**
Found this small bug while working on another PR.
If using an alternative EXE for hyperplay games or sideloaded games it won't check correctly if it is available or not, it will always check the original exe.

### To Test
- Delete or rename the game EXE.
- Going to the game page it will show as game not available.
- Go to the game settings and select an alternative EXE. For instance, the renamed one.
- On `main` and stable it will keep saying that the game is not available.
- On this branch it should show as game available and then launch the alternative EXE.

Related QASE Suites:
- https://app.qase.io/project/HC?suite=72&previewMode=modal&case=360
- https://app.qase.io/project/HC?suite=72&previewMode=modal&case=361

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by jiyuu-jin — APPROVED** [review]

**Comment by BrettCleary** [comment]
can we put these steps in a qase test @flavioislima 
> Delete or rename the game EXE.
Going to the game page it will show as game not available.
Go to the game settings and select an alternative EXE. For instance, the renamed one.
On main and stable it will keep saying that the game is not available.
On this branch it should show as game available and then launch the alternative EXE.

**Comment by BrettCleary** [comment]
I think there was a regression when trying to launch a renamed exe that does not have an alternative exe set yet

On Main, this is what it looks like after clicking play on cosmik battle after renaming the exe
image

On this branch, this is what it looks like after clicking play on cosmik battle after renaming the exe 
image

**Review by eliobricenov — APPROVED** [review]

**Comment by flavioislima** [comment]
Good catch @BrettCleary was a missing `await` on the `launch` command. Just pushed a fix to it.

**Comment by nyghtstalker** [comment]
@flavioislima The Play button remains black after renaming and setting the alt EXE.

The game does launch correctly with the alt EXE and the purple does return to the Play button once the game is closed.

image
image

**Comment by flavioislima** [comment]
> @flavioislima The Play button remains black after renaming and setting the alt EXE.
> 
> The game does launch correctly with the alt EXE and the purple does return to the Play button once the game is closed.
> 
> image
> image
> 

Yeah, since this are different components they don't talk with each other in real time. So you need to get out and get back to the game page for it to check again if it's available or not.

**Review by BrettCleary — APPROVED** [review]
LGTM. Nice fix!

**Pull request merged**
