### PR TITLE
[Proxy] Support Struct Params

### PR DESCRIPTION
**Pull request by BrettCleary**
Struct params passed are passed from web3.unreal as strings. This PR parses these strings if the corresponding ABI type is a tuple.

To test, run this curl command in a bash terminal while hyperplay is running
```
curl --location --request POST "localhost:9680/sendContract" \
--header 'Content-Type: application/json' \
--data-raw '{
    "contractAddress": "0x2e0cb17ed5f24bfcbb30d61e195d90e06e388e1e",
    "functionName": "setWeapon",
    "params": ["1","[\"rifle\", \"2\", \"4\", \"3\"]"],
    "valueInWei": "0",
    "chain": {
        "chainId": "5"
    }
}'
```

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by flavioislima — APPROVED** [review]
LGTM!
Tested here and also works fine.

**Comment by enghamzasalem** [comment]
Hello guys! 
when it will be released?

**Comment by flavioislima** [comment]
> Hello guys! when it will be released?

We are aiming to release a new version this week, but there are a few other things to test and fix as well so we do not have an exact date.

**Comment by enghamzasalem** [comment]
Hello @flavioislima 

Hope you doing great?
Any updates for the release?

All the best

**Pull request merged**
