### PR TITLE
[Tech] Remove references to valistBaseApiUrlv1

### PR DESCRIPTION
**Pull request by jiyuu-jin**
<--- Put the description here --->

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by BrettCleary — APPROVED** [review]
nice. let's have @nyghtstalker test an access code gated game on this branch

**Comment by nyghtstalker** [comment]
@jiyuu-jin @BrettCleary I am getting this after starting in dev mode.

image

**Comment by BrettCleary** [comment]
Need to migrate `api/v1/license_contracts/validate/get-nonce` to hp dev

**Review by BrettCleary — APPROVED** [review]
LGTM. tested and got an rpc error from the backend but we can fix on a separate backend PR

**Pull request merged**
