### PR TITLE
[Fix] Pause and cancel for HP games

### PR DESCRIPTION
**Pull request by BrettCleary**
- implements the pause/resume on click buttons for download toast
- fixes canceling a paused HP game
- cleans up error handling and fixes an issue where paused games' temp zip dir would be attempted to be cleaned and removed
- fixes an issue where games needing update would show as installed
- fixes stop download button click on game card
- fixes hp games showing as 0/1KB due to MB being interpreted as Bytes

### testing
1. download hp game
2. Pause
3. cancel and keep files
4. download again
5. pause
6. resume
7. cancel but don't keep files
8. etc
9. repeat for hp, epic, and gog games

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Pausing is working fine, but for me it never cleans the files if I say that I don't want to keep the files when canceling:

```
ls -lh ~/Library/Application\ Support/hyperplay/.temp/6479543ce61cddebcbab7e09/
total 1048592
-rw-r--r--@ 1 flavio  staff   499M Jun  5 18:48 TheFabled.zip.$$0$PART
```

image

**Comment by flavioislima** [comment]
Not totally related with this PR but I think this dialog was not stylized:
image

**Comment by stormcakes** [comment]
On Step 4 of downloading Bionic Owls i start to see this 
image

**Comment by stormcakes** [comment]
Files also aren't being cleaned for me that I opt to not keep.

**Comment by stormcakes** [comment]
[Bug Video.zip](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/files/11659721/Bug.Video.zip)
Uploaded a zip with a video of the issues i'm seeing. 

- Starting new downloads takes a long time. 
- Starting a new download sometimes doesn't actually start it, it will start as "paused". 
- Sometimes restarting a download (after electing to keep files) will result in the path being null. 
- Files are not being cleaned when a user elects to not keep the files.

**Comment by BrettCleary** [comment]
> Starting a new download sometimes doesn't actually start it, it will start as "paused".

On your video, this occurred because you paused the download manager, canceled (removed item from download manager queue), and then added another game to the download manager queue which was still paused. This is the expected behavior as I intended it. maybe the designers or @flavioislima can chime in here as well. not sure if it is better ux to automatically resume the download manager every time someone adds an item to its queue

**Comment by BrettCleary** [comment]
> Files are not being cleaned when a user elects to not keep the files.

If you download a game that is cached on the cdn, it will download in chunks. if you elect to remove files, it should remove as many as it can. this still leaves 10-20 files though on windows because easydl has not released them. if you try to delete them thorugh the file manager it will not let you either. closing the app will delete the files though. this also prevents downloading, canceling but not keeping files and redownloading. I've discussed with @flavioislima and we need to submit a PR to easydl with a fix. for now, it seems to be a minor issue though and we elected to move forward so we could have download pausing

**Comment by BrettCleary** [comment]
> Starting new downloads takes a long time.

this is a separate issue unrelated to this PR that relates to cdn caching

**Comment by BrettCleary** [comment]
> Sometimes restarting a download (after electing to keep files) will result in the path being null.

I will look into this one. Is this the same issue as the "default" string in place of the path you saw in your video and screenshot above?

**Comment by BrettCleary** [comment]
> Pausing is working fine, but for me, it never clean the files if I say that I don't want to keep the files when canceling:
> 
> ```
> ls -lh ~/Library/Application\ Support/hyperplay/.temp/6479543ce61cddebcbab7e09/
> total 1048592
> -rw-r--r--@ 1 flavio  staff   499M Jun  5 18:48 TheFabled.zip.$$0$PART
> ```
> 
> image

can you delete these files manually? maybe easydl isn't releasing them on windows either? also do you have any logs? we can also add some more logging here https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/blob/8e32bf6d39b18f09f2b8c1a333caa426ac153a57/src/backend/storeManagers/hyperplay/games.ts#L388-L407 for debug purposes

**Comment by flavioislima** [comment]
@BrettCleary it works fine on 0.2.3, it removes all files if I click on remove them.
tested just now and then tested on this branch and it keeps the files.

I think this is not a minor issue because imagine if these remaining files are like 10GB of a non-finished the borneless or phantom galaxies, that was the one I tested just now.

I wonder if this is related with the removed try/catch block around the installGame method.

I understand that it was to fix the pausing though.

Perhaps we should replace the abortController there with an ipcCall since we have 2 states: abort and pause. Right now we are using  abort for everything so the code is not reliable. With one ipcCall we can send the command we need with the parameters we need:

Something like this:
`stopDownload(command: 'pause' | 'abort', keepFiles?: boolean)`

and then based on that we handle the correct behavior.

**Comment by stormcakes** [comment]
Yes, this one was the same as the above attached photo of the default
string.

**Comment by BrettCleary** [comment]
> Not totally related with this PR but I think this dialog was not stylized: image

fixed now

**Comment by flavioislima** [comment]
Getting back to test this one.
I noticed that on the terminal, I get the following error:
```get game info handle with runner hyperplay  and appname 63fd0f9f069b92b74c3abe9d
Error occurred in handler for 'getGameInfo': Error: App not found in library
    at Module.getGameInfo$5 [as getGameInfo] (/Users/flavio/develop/hyperplay-desktop-client/build/electron/main.js:4411:11)
    at /Users/flavio/develop/hyperplay-desktop-client/build/electron/main.js:26539:33
    at node:electron/js2c/browser_init:2:97909
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81422)
    at EventEmitter.emit (node:events:513:28)```
    
I can reproduce this constantly doing like this:
- Go to the store
- Go to any game that is not on your library
- Add to library
- Click the Back button

For me it shows the error 100% of the time, not sure if it is impacting anything though. But it seems it is calling getGameInfo for that game before its information is properly added to the JSON file. Some racing condition I believe.

**Comment by flavioislima** [comment]
One issue that I believe was not introduced on this PR but would be good and simple to fix, is that we are losing the Progress state once we navigate out of the downloads screen during a download:

image

Probably we have a default progress object that is not being updated correctly somewhere.

**Comment by flavioislima** [comment]
Another weird bug is that when clicking to uninstall a game, the library layout is shifting for some reason:
image

**Comment by flavioislima** [comment]
I can confirm that the files are being properly deleted when checking that the files will not be keept. I wonder if this checkbox should not be disabled by default, I think if a person is canceling the download they don't want to keep the files. 
But this is something we can discuss with the team later.

**Comment by flavioislima** [comment]
Another thing I noticed related to the new UI:
- I could not find the Platform filters.
- I think the store filters should show only the filters available. So if you are not logged in on GOG or Epic, they should not be shown.

**Comment by BrettCleary** [comment]
> One issue that I believe was not introduced on this PR but would be good and simple to fix, is that we are losing the Progress state once we navigate out of the downloads screen during a download:
> 
> image
> Probably we have a default progress object that is not being updated correctly somewhere.

yes I created an issue for this a while back https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/issues/225
we only handle the events on the frontend and don't store the state anywhere other than in that component

**Comment by BrettCleary** [comment]
> Another weird bug is that when clicking to uninstall a game, the library layout is shifting for some reason: image

I get the same issue on develop but not on main. looks like it is inserting a blank game card into the `GamesList` component for some reason. let's handle on a separate branch from develop

**Comment by BrettCleary** [comment]
> Another thing I noticed related to the new UI:
> 
> * I could not find the Platform filters.

platform filter? is that a filter we had in the previous design? I didn't see it in the figma either https://www.figma.com/file/GKPELZxk551oVC3EDLgEDA/HP-Launcher?type=design&node-id=3134-23045&t=WXhLqQ2WZOz0kAQ9-4


> * I think the store filters should show only the filters available. So if you are not logged in on GOG or Epic, they should not be shown.

i think that is a great idea. you already know I'm going to say separate branch :)

**Comment by BrettCleary** [comment]
> Getting back to test this one. I noticed that on the terminal, I get the following error:
> 
> ```
> get game info handle with runner hyperplay  and appname 63fd0f9f069b92b74c3abe9d
> Error occurred in handler for 'getGameInfo': Error: App not found in library
>     at Module.getGameInfo$5 [as getGameInfo] (/Users/flavio/develop/hyperplay-desktop-client/build/electron/main.js:4411:11)
>     at /Users/flavio/develop/hyperplay-desktop-client/build/electron/main.js:26539:33
>     at node:electron/js2c/browser_init:2:97909
>     at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81422)
>     at EventEmitter.emit (node:events:513:28)
> ```
> 
> I can reproduce this constantly doing like this:
> 
> * Go to the store
> * Go to any game that is not on your library
> * Add to library
> * Click the Back button
> 
> For me it shows the error 100% of the time, not sure if it is impacting anything though. But it seems it is calling getGameInfo for that game before its information is properly added to the JSON file. Some racing condition I believe.

this isn't really an error though. when you click the back button, it goes back to the main page with all the games and it calls `getInfo` on every game. this throws if the game isn't in the library

**Comment by flavioislima** [comment]
> > Another thing I noticed related to the new UI:
> > 
> > * I could not find the Platform filters.
> 
> platform filter? is that a filter we had in the previous design? I didn't see it in the figma either https://www.figma.com/file/GKPELZxk551oVC3EDLgEDA/HP-Launcher?type=design&node-id=3134-23045&t=WXhLqQ2WZOz0kAQ9-4
> 
> > * I think the store filters should show only the filters available. So if you are not logged in on GOG or Epic, they should not be shown.
> 
> i think that is a great idea. you already know I'm going to say separate branch :)


Yes, I just saw that it was removed from the Figma design but I asked billie to add it again because we should have it to be able to filter native, browser and non-native games.

**Comment by flavioislima** [comment]
Just a reminder to check and delete the old UI components that will not be used anymore. For instance: StoreFilter, PlatformFilter and others.

**Review by flavioislima — APPROVED** [review]
LGTM

**Review by stormcakes — APPROVED** [review]

**Comment by BrettCleary** [comment]
massive improvements have been made to our test suite on this branch despite that not being its purpose. 

this feature is passing all of our extensive manual acceptance tests as well so these issues are probably related to the tests themselves 

for that reason, I will merge and we can fix the remaining failing tests on a dedicated branch

**Pull request merged**
