### PR TITLE
[FIX] Improve default Compatibility Layer setup

### PR DESCRIPTION
**Pull request by flavioislima**
Closes https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/1045

Refactor the `getDefaultWine` method for better legibility and and fix not refreshing the wine list when called the first time.

### How to test (macOS and Linux)
- Make sure you dont have any downloaded wine or GPTK on your machine (delete the tools folder on hyperplay config folder on linux and mac)
- Start HyperPlay
- On Linux it should start downloading Wine-GE (can be seen on the logs or navigating quickly to Settings > Wine Manager)
- On MacOS it should download GPTK if you are on apple silicon and Sonoma or higher. Otherwise it will download Wine-Crossover.
- A notification should appear telling about the compatibility layer setup.

### CODE REVIEW

**Comment by BrettCleary** [comment]
could you add testing steps @flavioislima?

**Comment by flavioislima** [comment]
> could you add testing steps @flavioislima?

Done!

**Review by BrettCleary — APPROVED** [review]
LGTM. do you think @nyghtstalker should test on both mac and linux?

**Comment by flavioislima** [comment]
@BrettCleary yes, this should be tested on both on a clean install or at least removing all downloaded wine and proton versions available.

**Comment by nyghtstalker** [comment]
@flavioislima I deleted the HP folder and this is what was installed after launching. I do have a M1 on Sonoma 14.5. I wanted to confirm this is the expected behavior.

I did not get any notification. Nothing from the client or from the Mac. What notification should appear? Is there a specific way to trigger it since I didn't get it?

image

**Comment by flavioislima** [comment]
> @flavioislima I deleted the HP folder and this is what was installed after launching. I do have a M1 on Sonoma 14.5. I wanted to confirm this is the expected behavior.
> 
> I did not get any notification. Nothing from the client or from the Mac. What notification should appear? Is there a specific way to trigger it since I didn't get it?
> 
> image
> 

Can you paste the logs here? Can you also paste the Game settings screen with the list of wine versions opened?

**Comment by nyghtstalker** [comment]
> > @flavioislima I deleted the HP folder and this is what was installed after launching. I do have a M1 on Sonoma 14.5. I wanted to confirm this is the expected behavior.
> > I did not get any notification. Nothing from the client or from the Mac. What notification should appear? Is there a specific way to trigger it since I didn't get it?
> > image
> 
> Can you paste the logs here? Can you also paste the Game settings screen with the list of wine versions opened?

Please let me know if this is enough or if you need anything else, @flavioislima .

```(13:25:06) INFO:    [HyperPlay]:        HyperPlayAPI initialized
(13:25:06) INFO:    [HyperPlay]:        Extension provider initialized
(13:25:06) INFO:    [HyperPlay]:        Proxy server started
(13:25:08) INFO:    [Legendary]:        Legendary location: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(13:25:08) INFO:    [Gog]:              GOGDL location: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(13:25:09) INFO:    [Connection]:       Connectivity: check-online
(13:25:09) INFO:    [Connection]:       Pinging external endpoints
(13:25:09) INFO:    [Legendary]:        Legendary location: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(13:25:09) INFO:    [Gog]:              GOGDL location: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(13:25:09) INFO:    [Gog]:              GOGDL location: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(13:25:09) INFO:    [HyperPlay]:        Loading MetaMask extension
(13:25:09) INFO:    [HyperPlay]:        Overlay Initialized
(13:25:10) WARNING: [Backend]:          Protocol already registered.
(13:25:10) INFO:    [Backend]:          App is starting in headless mode = undefined isCLINoGui = false startInTray = undefined
(13:25:10) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(13:25:12) INFO:    [HyperPlay]:        MetaMask extension loaded
(13:25:14) INFO:    [Connection]:       Connectivity: online
(13:25:14) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(13:25:14) INFO:    [Backend]:          Creating abort controller for legendary-version
(13:25:14) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/joe/Library/Application Support/hyperplay/legendaryConfig" /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(13:25:15) INFO:    [Backend]:          Creating abort controller for gogdl-version
(13:25:15) INFO:    [Gog]:              Running command: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/joe/Library/Application Support/hyperplay/gog_store/auth.json" --version
(13:25:15) INFO:    [Backend]:          Spawned legendary with PID 29520
(13:25:15) INFO:    [Backend]:          Spawned gog with PID 29521
(13:25:15) INFO:    [Backend]:          LaunchDarkly client initialized
(13:25:15) INFO:    [Winetricks]:       Downloading Winetricks
(13:25:15) INFO:    [WineDownloader]:   Updating wine versions info
(13:25:15) INFO:    [WineDownloader]:   Fetching upstream information...
(13:25:15) INFO:    [Backend]:          Checking if macOS is Sonoma or higher
(13:25:16) INFO:    [Backend]:          macOS is Sonoma or higher
(13:25:16) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(13:25:16) INFO:    [DXVKInstaller]:    Updating dxvk-macOS to: dxvk-macOS-async-v1.10.3-20230507-repack
(13:25:16) INFO:    [Auth]:             Session started by unknown user with userID: unknown
(13:25:17) INFO:    [WineDownloader]:   Wine version list was updated
(13:25:17) INFO:    [WineDownloader]:   wine versions updated
(13:25:17) INFO:    [Backend]:          Checking if macOS is Sonoma or higher
(13:25:17) INFO:    [Backend]:          Creating abort controller for Wine-crossover-wine-23.7.1-1
(13:25:17) INFO:    [WineDownloader]:   Start installation of wine version Wine-crossover-wine-23.7.1-1
(13:25:17) INFO:    [Backend]:          macOS is Sonoma or higher
(13:25:17) INFO:    [Backend]:          App update is available
(13:25:21) INFO:    [Backend]:          Auto Updater found version: 0.18.2 released on 2024-09-10T22:05:12.790Z with name v0.18.2
(13:25:21) INFO:    [Backend]:          Frontend did not initialize after 10 seconds! Showing main window now
(13:25:22) INFO:    [DXVKInstaller]:    downloaded dxvk-macOS
(13:25:22) INFO:    [DXVKInstaller]:    extracting dxvk-macOS
(13:25:22) INFO:    [DXVKInstaller]:    dxvk-macOS updated!
(13:25:23) ERROR:   [Backend]:          Failed to update  Error: Could not get code signature for running application
    at Server.<anonymous> (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:168:36)
    at Object.onceWrapper (node:events:631:28)
    at Server.emit (node:events:517:28)
    at Server.emit (node:domain:489:12)
    at emitListeningNT (node:net:1851:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
(13:25:25) INFO:    [Backend]:          App update is downloaded
(13:25:27) INFO:    [Backend]:          Deleting abort controller for legendary-version
(13:25:28) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(13:25:28) INFO:    [Backend]:          
System Information:
CPU: 10x Apple M1 Pro
Memory: 17.18 GB (used: 7.92 GB)
GPUs:

OS:  14.5.0 (darwin)

Software Versions:
  HyperPlay: 0.18.1
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3

(13:25:30) INFO:    [Frontend]:         Setting up LaunchDarkly with context: {
  "kind": "user",
  "key": "33d42978-fe53-459d-95c9-6499cea76294",
  "appVersion": "0.18.1",
  "languageCode": "en"
}
(13:25:31) INFO:    [Backend]:          Frontend Ready
(13:25:31) INFO:    [Backend]:          Loading Screen Ready
(13:25:31) INFO:    [Frontend]:         Refreshing hyperplay Library
(13:25:31) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(13:25:31) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
(13:25:31) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(13:25:31) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
(13:25:32) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(13:25:32) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
(13:25:32) INFO:    [Backend]:          Creating abort controller for legendary-check-updates
(13:25:32) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME="/Users/joe/Library/Application Support/hyperplay/legendaryConfig" /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(13:25:32) INFO:    [Backend]:          Spawned legendary with PID 29633
(13:25:32) INFO:    [Backend]:          Creating abort controller for legendary-check-updates
(13:25:32) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME="/Users/joe/Library/Application Support/hyperplay/legendaryConfig" /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(13:25:36) INFO:    [Backend]:          Starting the Download Queue
(13:25:50) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(13:25:50) INFO:    [Backend]:          Creating abort controller for legendary-version
(13:25:50) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/joe/Library/Application Support/hyperplay/legendaryConfig" /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(13:25:50) INFO:    [Backend]:          Spawned legendary with PID 29711
(13:25:50) INFO:    [Backend]:          Creating abort controller for gogdl-version
(13:25:50) INFO:    [Gog]:              Running command: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/joe/Library/Application Support/hyperplay/gog_store/auth.json" --version
(13:25:50) INFO:    [Backend]:          Spawned gog with PID 29712
(13:25:50) INFO:    [Backend]:          Creating abort controller for legendary-version
(13:25:50) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/joe/Library/Application Support/hyperplay/legendaryConfig" /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(13:25:50) INFO:    [Backend]:          Creating abort controller for gogdl-version
(13:25:50) INFO:    [Gog]:              Running command: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/joe/Library/Application Support/hyperplay/gog_store/auth.json" --version
(13:25:51) INFO:    [Backend]:          Hyperplay: Setting autoLaunchHyperPlay to false (previous value: undefined)
(13:25:51) INFO:    [WineDownloader]:   Finished installation of wine version Wine-crossover-wine-23.7.1-1
(13:25:51) INFO:    [Backend]:          Deleting abort controller for Wine-crossover-wine-23.7.1-1
(13:25:51) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(13:25:51) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(13:25:51) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(13:25:52) INFO:    [Backend]:          Hyperplay: Setting wineVersion to {"wineserver":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/bin/wineserver","lib":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/lib","lib32":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/lib","bin":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/bin/wine64","name":"Wine Crossover - 23.7.1-1","type":"wine"} (previous value: {"bin":"","name":"Default Wine - Not Found","type":"wine"})
(13:25:52) INFO:    [Backend]:          Changing wine version to Wine Crossover - 23.7.1-1
(13:25:52) INFO:    [Backend]:          Hyperplay: Setting wineVersion to {"wineserver":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/bin/wineserver","lib":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/lib","lib32":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/lib","bin":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/bin/wine64","name":"Wine Crossover - 23.7.1-1","type":"wine"} (previous value: {"wineserver":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/bin/wineserver","lib":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/lib","lib32":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/lib","bin":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/bin/wine64","name":"Wine Crossover - 23.7.1-1","type":"wine"})
(13:25:52) INFO:    [Backend]:          Hyperplay: Setting wineVersion to {"wineserver":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/bin/wineserver","lib":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/lib","lib32":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/lib","bin":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/bin/wine64","name":"Wine Crossover - 23.7.1-1","type":"wine"} (previous value: {"wineserver":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/bin/wineserver","lib":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/lib","lib32":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/lib","bin":"/Users/joe/Library/Application Support/hyperplay/tools/wine/Wine-crossover-wine-23.7.1-1/Contents/Resources/wine/bin/wine64","name":"Wine Crossover - 23.7.1-1","type":"wine"})
(13:25:52) INFO:    [Backend]:          Hyperplay: Setting autoLaunchHyperPlay to false (previous value: false)
(13:25:52) INFO:    [Backend]:          Hyperplay: Setting autoLaunchHyperPlay to false (previous value: false)
(13:26:00) INFO:    [Backend]:          Deleting abort controller for legendary-check-updates
(13:26:00) DEBUG:   [Legendary]:        Update is available for Kinglet: 1.0.12.918298_coppa_Kinglet != 1.0.12.951533_nebraska_update1_Kinglet
(13:26:00) DEBUG:   [Legendary]:        Update is available for KingletAztec: 1.0.12.918298_coppa_KingletAztec != 1.0.12.951533_nebraska_update1_KingletAztec
(13:26:00) INFO:    [Legendary]:        Found 2 games to update
(13:26:00) INFO:    [Backend]:          Deleting abort controller for legendary-check-updates
(13:26:00) DEBUG:   [Legendary]:        Update is available for Kinglet: 1.0.12.918298_coppa_Kinglet != 1.0.12.951533_nebraska_update1_Kinglet
(13:26:00) DEBUG:   [Legendary]:        Update is available for KingletAztec: 1.0.12.918298_coppa_KingletAztec != 1.0.12.951533_nebraska_update1_KingletAztec
(13:26:00) INFO:    [Legendary]:        Found 2 games to update
(13:26:00) INFO:    [Legendary]:        Auto-Updating Sid Meier's Civilization VI
(13:26:00) INFO:    [Legendary]:        Auto-Updating Sid Meier's Civilization VI
(13:26:03) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:26:03) INFO:    [Legendary]:        Auto-Updating Civilization VI : Aztec DLC
(13:26:03) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:26:03) INFO:    [Legendary]:        Auto-Updating Civilization VI : Aztec DLC
(13:26:03) INFO:    [Backend]:          Preventing machine to sleep
(13:26:03) INFO:    [Backend]:          Creating abort controller for Kinglet
(13:26:03) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/joe/Library/Application Support/hyperplay/legendaryConfig" /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info Kinglet --json --platform Windows
(13:26:03) INFO:    [Backend]:          Spawned legendary with PID 29826
(13:26:03) INFO:    [Backend]:          Creating abort controller for Kinglet
(13:26:03) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/joe/Library/Application Support/hyperplay/legendaryConfig" /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info Kinglet --json --platform Windows
(13:26:05) INFO:    [Backend]:          Deleting abort controller for legendary-version
(13:26:05) INFO:    [Backend]:          Deleting abort controller for legendary-version
(13:26:06) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:26:06) INFO:    [Gog]:              Found 0 game(s) to update
(13:26:06) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:26:06) INFO:    [Gog]:              Found 0 game(s) to update
(13:26:06) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(13:26:06) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(13:26:06) INFO:    [Backend]:          Creating abort controller for KingletAztec
(13:26:06) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/joe/Library/Application Support/hyperplay/legendaryConfig" /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info KingletAztec --json --platform Windows
(13:26:06) INFO:    [Backend]:          Spawned legendary with PID 29849
(13:26:06) INFO:    [Backend]:          Creating abort controller for KingletAztec
(13:26:06) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/joe/Library/Application Support/hyperplay/legendaryConfig" /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info KingletAztec --json --platform Windows
(13:26:29) INFO:    [Backend]:          Deleting abort controller for Kinglet
(13:26:29) INFO:    [Backend]:          Deleting abort controller for Kinglet
(13:26:31) INFO:    [Backend]:          Deleting abort controller for KingletAztec
(13:26:31) INFO:    [Backend]:          Deleting abort controller for KingletAztec
(14:25:10) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(14:25:10) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
```

**Comment by flavioislima** [comment]
@nyghtstalker 
There was an issue with the logic, should be fixed now.
Can you test again when you have the time?

**Review by nyghtstalker — APPROVED** [review]
Confirmed that GPTK is auto installed after launching a fresh client. 

I also confirmed that if you launch a Window compatiable game on Mac with no compatibility Layer setup it will auto install it and launch the game! LFG!!!

image

**Pull request merged**
