### PR TITLE
[Quests] Update quest details UI 

### PR DESCRIPTION
**Pull request by BrettCleary**
# Summary
Updates client to get quest from the dev portal and pass play streak eligibility to `QuestDetails` UI component

### CODE REVIEW

**Review by eliobricenov — APPROVED** [review]
lgtm

**Review by red-game-dev — APPROVED** [review]
LGTM

**Review by flavioislima — APPROVED** [review]
good stuff

**Comment by nyghtstalker** [comment]
When selecting other quests the playstreak info is flashing and then disappears. After going back to the games the flashing no longer occurs.


https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/b0c03c44-283a-4bec-bb3e-eb560969f35a

**Comment by nyghtstalker** [comment]
I am seeing the playstreak details displayed on the Quests page and in the overlay when selecting the appropriate quest.

image
image

**Review by nyghtstalker — APPROVED** [review]
The playstreak flashing will be handled on a different PR.

**Pull request merged**
