### PR TITLE
[TECH] Remove Nile and Amazon Integration

### PR DESCRIPTION
**Pull request by flavioislima**
This is a long one but it is basically code removal so testing is appreciated. 

### To test

- Just be sure that all information for Amazon store is gone from the App in places like: Login Screen, Library filters, logs, etc.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by BrettCleary** [comment]
Appreciate the clean up!

I was only able to find a few remaining references to nile in the package.json
image

**Review by BrettCleary — APPROVED** [review]
red is a great color! less to maintain! woot! 💃

**Comment by red-game-dev** [comment]
> red is a great color! less to maintain! woot! 💃

Ofc is good color, is part of my name! 😆

**Review by red-game-dev — APPROVED** [review]

**Comment by flavioislima** [comment]
> Appreciate the clean up!
> 
> I was only able to find a few remaining references to nile in the package.json image

good catch!

**Comment by nyghtstalker** [comment]
I am unable to locate any Amazon content or related options - before and after the removal.

image

image

**Review by nyghtstalker — APPROVED** [review]

**Pull request merged**
