### PR TITLE
[UI/UX] Show store links on navbar on all pages and adjust it to small window sizes

### PR DESCRIPTION
**Pull request by flavioislima**
Small change to increase the discoverability of other stores on HyperPlay.
Also adjust the navbar and filters to small window sizes.

image

image

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by eliobricenov — APPROVED** [review]

**Review by red-game-dev — APPROVED** [review]

**Comment by flavioislima** [comment]
Ok so did some adjustments here to the minimum Window size:
Minimum supported resolution: Steam Deck one: 1280x800
Based on that, the minimum window size is equal ~66% or 1.5 of it. This way HP can still be opened with another APP and do not take the whole screen even on small screens like it. On 1080p screens resolution (most common ones) this will mean 44% of the screen. so seems like I reasonable size.

Based on that did the following changes for when the window is at the minimum size:
- Hide the HyperPlay Logo Text, kept only the logo itself
- Hide the Alpha badge
- Lowered the width of the Search bar when opened to 243px.

image

**Review by BrettCleary — APPROVED** [review]
nice. I think you need to run prettier again btw

**Comment by flavioislima** [comment]
> nice. I think you need to run prettier again btw

this is happening more often than I want to. Maybe we should get back to add lint on the pre-push command.

**Review by nyghtstalker — APPROVED** [review]
This looks AWESOME! I love all these much needed improvements to a smaller screen! It was def needed when viewing the previous on Main! I love that the stores are now accessible from all the side nav pages! Great job!

image

**Pull request merged**
