### PR TITLE
[FIX] Wrong info on Download Manager

### PR DESCRIPTION
**Pull request by flavioislima**
Fixes:
- Wrong store name for HyperPlay Games
- Missing Install size on some games
- Missing Date of start and completition

Captura de imagem_20240911_125052
 

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by eliobricenov — APPROVED** [review]

**Review by BrettCleary — APPROVED** [review]

**Comment by nyghtstalker** [comment]
1. The size is duplicated from the previous on the Downloaded tab.

image

2. Download info is still displayed after the download is complete on all tabs.

image
image
image

However, this all only occurs while on the page. Once the user leaves and returns to the downloads page the info is displayed correctly. Just need to get it corrected to show correctly from the start and not needing to leave and come back. @flavioislima 

image

**Comment by flavioislima** [comment]
@nyghtstalker fixed both comments now.

**Comment by nyghtstalker** [comment]
1. Asking for approval from designers about hiding the download graph while not downloading. 
https://hyperplay-workspace.slack.com/archives/C05RM1P50BT/p1727112916034539

2. Looks like the size is still being duplicated from the previous line on the initial install on the Downloaded tab. Leaving page and returning still corrects the issue.

image
image
image
image

**Comment by flavioislima** [comment]
@nyghtstalker the download size should be fixed now on the latest commit:
image

**Review by nyghtstalker — APPROVED** [review]
The size is displaying correctly.

image

**Pull request merged**
