### PR TITLE
[FIX] Platform selection on Add Game screen

### PR DESCRIPTION
**Pull request by flavioislima**
Fix the platform selection when sideloading a game.
I thought this was fixed already but I was mistaken.

image

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Also changed the behavior of the warning message to be opened by default, there is a ticket for that:
image

**Comment by stormcakes** [comment]
Verified warning appears on initial load 
image

**Comment by stormcakes** [comment]
Verified Windows/Browser are only options on Windows machines. Checking others now.. 
image

**Review by stormcakes — APPROVED** [review]

**Comment by BrettCleary** [comment]
working for me. nice! I will let @stormcakes finish testing and approve

**Comment by stormcakes** [comment]
Sorry for the delay! 
image

**Pull request merged**
