### PR TITLE
[Tech] Refactor to use quests ui quest details

### PR DESCRIPTION
**Pull request by BrettCleary**
# Summary 

- Refactor to use `QuestDetailsWrapper` from `@hyperplay/quests-ui`
- Update to latest HP UI. passing the search bar as a component to quest summary table

# Testing
Test all existing quest details qase tests 
the following quests should work

- test quest erc20 8.13.24
- HyperPlay erc721 testing quest
- HyperPlay erc20 testing quest
- points test 2

### CODE REVIEW

**Review by red-game-dev — APPROVED** [review]
LGTM 🚀 Cheers for porting the markdown too 🙌

**Review by eliobricenov — APPROVED** [review]

**Review by jiyuu-jin — APPROVED** [review]

**Comment by nyghtstalker** [comment]
1. Quest "points test 2" and the spacing in this looks wrong. Here is what it looks like in main but I am guessing it does not have the markup included?

   image
   image

2. I claimed this once and I am able to claim it again. Is there any situation where this is acceptable?

   image
   image
   image

3. "Claim failed" carrying over when changing quests

   image

4. I claimed this and it went straight to 1/7. I have been on this game for a bit but should it change to 1/7 after claiming?

   image

5. Should markup be in-game quest details? 

   image

**Comment by BrettCleary** [comment]
@nyghtstalker 1 and 5 should be handled now. 4 is possible several different scenarios so I'm not worried about that.

**Comment by BrettCleary** [comment]
@nyghtstalker I believe 3 is is the same on main right? if so, I will not be fixing on this branch

**Comment by BrettCleary** [comment]
@nyghtstalker For 2, the quest is repeatable and you claimed several days ago, so this is fine

**Review by nyghtstalker — APPROVED** [review]
Quest details look much better. Confirmed that my third issues does occur on `main` so I will ignore that one. Everything else looks good.

image

**Pull request merged**
