### PR TITLE
[FIX] Linux Menu Icon for AUR, DEB and RPM

### PR DESCRIPTION
**Pull request by flavioislima**
- Regenerated a new ICNS icon since the previous one was failing to convert to PNG.
- No need to define the icon on package.json since it will use the icns as default.

### Testing

Since I changed the ICNS file, it's good to test on macOS to be sure that the icon is fine there as well.
@nyghtstalker On Linux you can generate a .deb (`yarn dist:linux deb`) and try it on Linux Mint. Or generate a .pacman (`yarn dist:linux pacman`) and test on Arch Linux (install with: `sudo pacman -U /path/to/hyperplay.pacman`.

The Icon should work fine on both the Start Menu and on the taskbar.

image

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by BrettCleary** [comment]
I can confirm this is working on ubuntu with the .deb artifact

image
image

**Review by nyghtstalker — APPROVED** [review]
Confirmed I am seeing the HP icon in the toolbar for Mac.

The HP icon is larger than all the other icons though... Heads up, @flavioislima.

image

**Comment by BrettCleary** [comment]
I can confirm the flatpak icon is showing on arch linux
image

**Comment by BrettCleary** [comment]
the executable in the tar.xz is showing the icon correctly as well

**Comment by BrettCleary** [comment]
I can confirm the pacman icon is showing as well

**Review by BrettCleary — APPROVED** [review]
LGTM

**Comment by flavioislima** [comment]
> Confirmed I am seeing the HP icon in the toolbar for Mac.
> 
> The HP icon is larger than all the other icons though... Heads up, @flavioislima.
> image

interesting, maybe because I used the png file, so we need to leverage what is worse then, keep the missing icon on linux or having a bigger icon on macOS. What do you guys think?

**Comment by flavioislima** [comment]
I can fix the icon size another time since I fixed it last time

**Comment by BrettCleary** [comment]
> interesting, maybe because I used the png file, so we need to leverage what is worse then, keep the missing icon on linux or having a bigger icon on macOS. What do you guys think?

oh I thought we still had this issue previously on mac. didn't know you fixed it

could we override the icon just for mac to the png then?

**Comment by BrettCleary** [comment]
> I can fix the icon size another time since I fixed it last time

I am also fine with fixing this later. it is a minor issue. the missing linux icon is a major issue

**Pull request merged**
