### PR TITLE
[Feat] Add go back and go forward arrows to browser games

### PR DESCRIPTION
**Pull request by BrettCleary**
# Summary

Adds go back and go forward arrow icon buttons to browser games.

### Note
I attempted to set the disabled boolean based on `webview.canGoBack` but there was an issue attempting to use `webview.current` before the `"dom-ready"` event had fired. Correct me if I'm wrong, but I don't think this is a blocker.

image

# Testing
https://app.qase.io/project/HC?case=332&previewMode=modal

### CODE REVIEW

**Review by red-game-dev — APPROVED** [review]
LGTM 🙌

**Comment by flavioislima** [comment]
> I attempted to set the disabled boolean based on webview.canGoBack but there was an issue attempting to use webview.current before the "dom-ready" event had fired. Correct me if I'm wrong, but I don't think this is a blocker.

i think we solved this on the main Webview.
One approach is to use a state for the disabled button and change it on a useEffect after the `dom-ready` event is received or something like it.

**Comment by BrettCleary** [comment]
@flavioislima I completely forgot about that `WebviewControls` component. I'll just use that one instead!

image

Fixed the stacking issue with the hint text with the overlay

image

**Review by flavioislima — APPROVED** [review]
Looks great!

**Review by nyghtstalker — APPROVED** [review]
This is awesome! Super simple and works great! Awesome work!

**Pull request merged**
