### PR TITLE
[UI/UX] Improve Log screen with game list and categories

### PR DESCRIPTION
**Pull request by flavioislima**
Improve the Log screen on settings:

Screenshot 2024-03-20 at 12 04 51

Description from the [original PR](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3147):

> This PR changes the general Logs screen to allow users to see not only the general log but also the logs for legendary/gogdl/nile and the logs for each of the currently installed apps/games.

> https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/bba8429b-8edd-404a-b8a1-b23a4b055d6c
> 
> I removed the option to the the old general log on purpose since I don't think is ever used by users (when we ask for logs we want to see the most recent one). It also frees up some space for all the new options.
> 
> The motivations to do this are:
> - it makes it easier for use when we ask users for the specific runner logs
> - hopefully now users looking for games logs will see them in the sidebar and click there, since it happens too often that we ask for games logs and users share general logs
> - this adds more visibility in general to the end user, easier to discover information
> 
> If anybody needs the previous logs they can still open the logs folder and look for them, but I'd consider that a more advanced usage.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by eliobricenov** [comment]
Maybe it is worth reaching design time to double check the look and feel?

**Comment by flavioislima** [comment]
> Maybe it is worth reaching design time to double check the look and feel?
> 

On this pr I would like to only grab heroic changes.
Also because depending on the design I need to develop something on the UI lib which increase a lot the scope imo.

**Comment by flavioislima** [comment]
> Maybe it is worth reaching design time to double check the look and feel?
> 

I will do but I would prefer to change the design on another PR since changes like this might require implementing something on HP-UI as well and will increase the scope of the PR.

**Review by red-game-dev — APPROVED** [review]

**Comment by nyghtstalker** [comment]
I spoke with Flavio about these and they will be addressed in a later PR.

1. Some games display "No log file found". These will be hidden in the future if there is nothing to display.

image

2. Possibly duplication (this could be due to changes from the game devs)

image

**Review by nyghtstalker — APPROVED** [review]
Loving the extra logs to help diagnosis issues! Great job!

**Pull request merged**
