### PR TITLE
[FIx] Add eip6963 support

### PR DESCRIPTION
**Pull request by BrettCleary**
# Summary
Add eip 6963 support to injected provider

# Testing
https://app.qase.io/project/HC?case=349

### CODE REVIEW

**Review by jiyuu-jin — APPROVED** [review]
Amazing, looks perfect to the spec!

**Review by eliobricenov — APPROVED** [review]
worked perfectly for me


image

**Review by red-game-dev — APPROVED** [review]

**Comment by nyghtstalker** [comment]
If wallet is locked nothing appears on the overlay and there is no way to access it from the overlay

image

**Review by nyghtstalker — APPROVED** [review]

**Comment by BrettCleary** [comment]
> If the wallet is locked nothing appears on the overlay and there is no way to access it from the overlay. The user has to leave the game and unlock the wallet in the client before they can proceed.
> 
> image

will handle this one on a separate PR

**Pull request merged**
