### PR TITLE
[UI] added alert card to add-sideload-game modal

### PR DESCRIPTION
**Pull request by hellowodl**
<--- Put the description here --->

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Can you add a screnshot on how it looks, @hellowodl ?

**Comment by BrettCleary** [comment]
> Can you add a screnshot on how it looks, @hellowodl ?

image

image

**Review by BrettCleary — APPROVED** [review]
LGTM

**Comment by hellowodl** [comment]
> Can you add a screnshot on how it looks, @hellowodl ?

Shoot. I hadn't seen your message.

Thanks a lot making the screenshot @BrettCleary

**Pull request merged**
