### PR TITLE
Feature flag Amazon Game Store

### PR DESCRIPTION
**Pull request by BrettCleary**
Add feature flag for AGS. Disable it.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by nyghtstalker** [comment]
- Amazon has been removed from the Store, Library, and Manage Accounts pages.

image

image

image

**Review by nyghtstalker — APPROVED** [review]
Good job! Amazon has VANISHED!

**Review by eliobricenov — APPROVED** [review]
lgtm!

I'm curious why you decided to replace `&&` with ternaries? 👀

**Comment by BrettCleary** [comment]
> lgtm!
> 
> I'm curious why you decided to replace `&&` with ternaries? 👀

@eliobricenov 
ah this is a good article but they paywalled it https://medium.com/geekculture/stop-using-for-conditional-rendering-in-react-a0f7b96200f8

basically if you render with 
```
return {false && <div>something</div>}
```

it'll render a 0 in the DOM because false is rendered and converted into a number

if you use a ternary it will just return null and nothing will be rendered

maybe we haven't been seeing theses 0's in this case because mantine filters them out, but we should use ternary anyways. it is less error prone. I have seen these random 0's from `&&` before and they can be pretty hard to track down

**Pull request merged**
