### PR TITLE
[Quests] Post playsession on game close

### PR DESCRIPTION
**Pull request by BrettCleary**
# Summary

Post play session time to playStreak endpoint on game close

# Testing
1. Log in with HP account
2. Launch Kosium
3. Close kosium
4. check db for updated play session time

### CODE REVIEW

**Review by eliobricenov — APPROVED** [review]

**Review by red-game-dev — APPROVED** [review]

**Comment by BrettCleary** [comment]
Noting here that there seems to be an issue with tracking GPTK launched games on Mac

**Comment by BrettCleary** [comment]
> Noting here that there seems to be an issue with tracking GPTK launched games on Mac

unable to reproduce on mac, so I am moving this into testing

**Comment by nyghtstalker** [comment]
1. Buttons are missing on the library game pages

image
image


2. With the wallet locked and you select the last quest it will turn the whole screen gray. I am sure it is because the wallet is locked is this ok and expected behavior? It is certainly confusing for an unknowing player as to what is going on.

image
image

3. Clicking the same quest on the Quests page causes the whole click to go black and I have to close the entire client to fix it.

image
image

**Comment by nyghtstalker** [comment]
> 1. Buttons are missing on the library game pages
> 
> image image
> 
> 2. With the wallet locked and you select the last quest it will turn the whole screen gray. I am sure it is because the wallet is locked is this ok and expected behavior? It is certainly confusing for an unknowing player as to what is going on.
> 
> image image
> 
> 3. Clicking the same quest on the Quests page causes the whole click to go black and I have to close the entire client to fix it.
> 
> image image

I confirmed that #2 and #3 are occurring on `main`, too.

**Review by flavioislima — APPROVED** [review]

**Review by nyghtstalker — APPROVED** [review]

**Pull request merged**
