### PR TITLE
[FEAT-macOS] Add Whisky support

### PR DESCRIPTION
**Pull request by flavioislima**
Add support for finding and using Whisky's GPTK installed on the system.

Since Wine-Crossover still does not support d3dmetal, should be fixed on the next release, this is the easiest way to use it.

[Whisky is a tool that automates and simplifies installing GPTK on macOS and more.](https://getwhisky.app/)

It also includes a small fix to use Crossover on GOG games.

### To test.

- On macOS Sonoma or later
- Download and install Whisky app: https://getwhisky.app/
- Open it and it will ask to install the GPTK on your system
- Wait for the installation.
- Open HyperPlay and select a windows games (The fabled for instance) or any other.
- On the game settings, look for (Whisky - version. For instance: Whisky - 2.2) and select it as runner.
- Make sure you are using a clean prefix, if the prefix has DXVK installed on it the game will fail to load.
- Enable the stats overlay on the game settings to see if it will show Rosetta x64
- If it shows the overlay and the game loads and it shows Rosetta x64 then it is working.
- NOT all games will work. Tried with the fabled and worked fine, without the GPTK it runs pretty bad and slow.
- If it shows a warning about AMD drivers just ignore it.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by eliobricenov — APPROVED** [review]
code lgtm - let's wait for @nyghtstalker to test implementation

**Review by red-game-dev — APPROVED** [review]
LGTM 🍾 

Interesting and lovely name xD

**Review by BrettCleary — APPROVED** [review]
lgtm!

**Review by nyghtstalker — APPROVED** [review]
I had some issues with the prereq installation but I eventually got to the point where it fails (which seems to be the expected behavior) and then able to launch the game after. 

image

**Pull request merged**
