### PR TITLE
[Tech] Move to Electron-Vite

### PR DESCRIPTION
**Pull request by flavioislima**
Related PRs:
https://github.com/HyperPlay-Gaming/hyperplay-overlay/pull/7
https://github.com/HyperPlay-Gaming/hyperplay-extension-helper/pull/42

PR based on the Heroic one:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3218

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by BrettCleary** [comment]
getting the white screen error after deleting `build`, `dist`, `node_modules`, running `yarn setup` then `yarn start`
image

**Comment by flavioislima** [comment]
> getting the white screen error after deleting `build`, `dist`, `node_modules`, running `yarn setup` then `yarn start`
> image
> 

Did you also changed the submodules branches?

**Review by BrettCleary — APPROVED** [review]
LGTM

**Review by red-game-dev — APPROVED** [review]

**Comment by flavioislima** [comment]
I am merging this one to stop blocking the other PRs.
We can do a regression test afterward.

**Pull request merged**
