### PR TITLE
[Fix] WalletConnect and MetaMask Mobile Connected States

### PR DESCRIPTION
**Pull request by BrettCleary**
Fixes isConnected on wallet connect provider
Fixes notification of connection of metamask mobile sdk

#### MetaMask Mobile
1. Connect with MetaMask
2. Check that the modal closes when you click connect on your phone

#### Wallet Connect
1. Wallet Connect
2. Connect with wallet connect 
3. Run 
```
curl -H "content-type:application/json" -X POST -d "{\"request\":{\"method\":\"eth_accounts\"},\"chain\":{\"chainId\":\"1\"}}" http://localhost:9680/rpc
```
4. Check that a string array of length 1 with the connected public address is returned
---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Tested here the MetaMask part and one thing is that it now shows on HP that it was connected but when I try to play a game like Defi Kingdom the game never detects my wallet when I click connect. So I cannot play with the wallet on the phone.
Not sure if its related to this or the MM SDK.

**Comment by flavioislima** [comment]
Got this on the terminal when I click Connect Wallet:
```
MetaMask - RPC Error: The method send does not exist/is not available {
  code: -32601,
  message: 'The method send does not exist/is not available'
}```

**Comment by BrettCleary** [comment]
> Got this on the terminal when I click Connect Wallet:
> 
> ```
> MetaMask - RPC Error: The method send does not exist/is not available {
>   code: -32601,
>   message: 'The method send does not exist/is not available'
> }```
> ```

Here's the full error message 
```
MetaMask: 'ethereum.send(...)' is deprecated and may be removed in the future. Please use 'ethereum.sendAsync(...)' or 'ethereum.request(...)' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193
MetaMask - RPC Error: The method send does not exist/is not available {
  code: -32601,
  message: 'The method send does not exist/is not available'
}
```

The problem is that DFK uses the deprecated `send` method and metamask mobile finally stopped supporting it. If you try to connect with the MetaMask extension, the connection works fine since the extension hasn't removed support for it yet.

We should let the developers know

**Comment by BrettCleary** [comment]
I would recommend running curl commands to test the connection with metamask/wallet connect. these commands can be found on https://docs.hyperplaygaming.com under the api examples sections.

we also have the proxy unit test `yarn testProxy` where you can scan the bar code in the terminal and it will go through a series of automated calls to the proxy server @flavioislima @stormcakes

**Comment by stormcakes** [comment]
to run this proxy unit test would this be possible via the artifacts or
would i need to run a local build of it? @brett

**Comment by stormcakes** [comment]
Also seeing the issue when scanning QR Codes for Wallet Connect where it's not working in general. Tried Ledger and Phantom on Windows OS. Will try other OS to double check. For Phantom it says "The QR code is not valid" modal. Via Ledger it just never registers. However, Metamask Mobile connect and extension are working for me.

**Review by stormcakes — APPROVED** [review]
Tested and approved :)

**Pull request merged**
