### PR TITLE
[FIX] Games Auto Update

### PR DESCRIPTION
**Pull request by flavioislima**
This fixes auto-update that was broken due to a bad import.

### HOW TO TEST
- Enable Auto update games on startup on HyperPlay General Settings
- With some game with updates on the library, restart the app.
- The game shuld be added to the queue and start downloading automatically.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by eliobricenov — APPROVED** [review]

**Review by BrettCleary — APPROVED** [review]
nice fix

**Comment by BrettCleary** [comment]
@nyghtstalker can you add the issues you found with this PR here

**Comment by nyghtstalker** [comment]
image
image
image
image
image
image

**Comment by nyghtstalker** [comment]
From Mac testing:

- After loading the PR artifact I

**Comment by flavioislima** [comment]
> From Mac testing:
> 
> - After loading the PR artifact there are several games that still need to be updated
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 

This is the wrong checkbox @nyghtstalker @BrettCleary

The correct one is the Auto update games on startup.

This one only checks for client updates.

**Comment by flavioislima** [comment]
@nyghtstalker 
About that error with PCGamingWiki info, that one is broken for a long time now, fixed in heroic though. can pull the fix on another PR. Not related with this one though. This information is about showing the how long to beat the game and the scores.

There are two Epic games that I can't really update on auto-update here on my machine that are:
CIV VI and Kernal Space Program.

Tried in Heroic and it also does not work there for some reason.

About HP games, did you find any that did not update automatically?

**Comment by nyghtstalker** [comment]
I am seeing it update the games when I launch the app. From what I can tell all the HP games I tested did update.

image

@flavioislima However, I ran into this stuck modal and won't download after I manually changed the version of the game. I changed the version, launched it, closed the game, and then the modal appeared. I am seeing this error which I am unsure is related. Looks like it tried to download the correct version but it failed.

image

```(14:44:06) INFO:    [Backend]:          Aborting 0xa4f4e9306d4d179f9efea153b8b6c59da6d7ffc1ee904bdfc8e89d3ead831d81

(14:44:06) INFO:    [Backend]:          Aborted 0xa4f4e9306d4d179f9efea153b8b6c59da6d7ffc1ee904bdfc8e89d3ead831d81

(14:44:06) INFO:    [Backend]:          Canceled Wizarre_1_2_0_PROD.zip

(14:44:06) INFO:    [Backend]:          Deleting abort controller for 0xa4f4e9306d4d179f9efea153b8b6c59da6d7ffc1ee904bdfc8e89d3ead831d81

(14:44:08) INFO:    [Backend]:          Trying to kill J:\Users\Joe\Games\HyperPlay\flyingcactus\wizarre\wizarre.exe

(14:44:09) INFO:    [Backend]:          Killed J:\Users\Joe\Games\HyperPlay\flyingcactus\wizarre\wizarre.exe

(14:44:09) INFO:    [HyperPlay]:        Error while downloading and extracting game: Error: EBUSY: resource busy or locked, unlink '\\?\J:\Users\Joe\Games\HyperPlay\flyingcactus\wizarre\.temp\0xa4f4e9306d4d179f9efea153b8b6c59da6d7ffc1ee904bdfc8e89d3ead831d81\Wizarre_1_2_0_PROD.zip'

(14:44:09) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 0xa4f4e9306d4d179f9efea153b8b6c59da6d7ffc1ee904bdfc8e89d3ead831d81

(14:44:09) ERROR:   [DownloadManager]:  Update of 0xa4f4e9306d4d179f9efea153b8b6c59da6d7ffc1ee904bdfc8e89d3ead831d81 failed with: 

(14:44:09) WARNING: [DownloadManager]:  Update of 0xa4f4e9306d4d179f9efea153b8b6c59da6d7ffc1ee904bdfc8e89d3ead831d81 failed!

(14:44:09) INFO:    [DownloadManager]:  0xa4f4e9306d4d179f9efea153b8b6c59da6d7ffc1ee904bdfc8e89d3ead831d81 added to download manager finished.

(14:44:09) INFO:    [DownloadManager]:  0xa4f4e9306d4d179f9efea153b8b6c59da6d7ffc1ee904bdfc8e89d3ead831d81 removed from download manager.

(14:44:09) INFO:    [Frontend]:         Refreshing hyperplay Library

(14:44:09) INFO:    [Backend]:          Stopping Power Saver Blocker

(14:44:09) INFO:    [HyperPlay]:        Getting install info for Wizarre
```
image

**Comment by flavioislima** [comment]
This `  Error while downloading and extracting game: Error: EBUSY: resource busy or locked, unlink '\\?\J:\Users\Joe\Games\HyperPlay\flyingcactus\wizarre\.temp\0xa4f4e9306d4d179f9efea153b8b6c59da6d7ffc1ee904bdfc8e89d3ead831d81\Wizarre_1_2_0_PROD.zip'
` is actually another issue that @BrettCleary was looking into. Will be fixed on another PR if it wasn't already.

**Review by nyghtstalker — APPROVED** [review]
Confirmed that games auto update on launch and refresh button.

**Pull request merged**
