### PR TITLE
[Fix] Preserve symlinks during extraction

### PR DESCRIPTION
**Pull request by BrettCleary**
Recreates symlinks after a zip file is extracted

### Testing
Test with synergy of serra native mac build latest main release
- `Synergy of Serra Genesis.app/Contents/Frameworks/Electron Framework.framework/*` are all simlinks. You can verify with ls -l which will return `lrwxrwxrwx` in the first column. `l` is for "link"

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by red-game-dev** [comment]
Seems I'll need to apply these as soon as merged to my extraction PR, since that method no longer exists and we got a class instead `ExtractZipService`

**Comment by nyghtstalker** [comment]
This is also occurring on MCVERSE with their MAC build (which is now disabled due to this issue).
https://hyperplay-workspace.slack.com/archives/C05RXC4S03A/p1704740561418779

**Comment by awantoch** [comment]
next attempt: use the native system unzip tool

**Comment by flavioislima** [comment]
Will do more testing on this other PR #702

**Pull request closed without merging**
