### PR TITLE
[FIX] Check if game is available on game launch

### PR DESCRIPTION
**Pull request by flavioislima**
Fix a regression where we stopped checking if the game is available before launching.
In case the executable or the game folder was deleted or moved it will show a message using the native dialog (necessary since it might be launched without GUI).

It shows an option to remove the game from the installed list as well:
imagem

## How to test

1. Rename a currently installed game folder
2. Launch the game from the game card or game page.
3. The dialog should show after the onboarding dialog.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by nyghtstalker** [comment]
There is a duplication in the displayed text and the window title. Your sample shows the game name instead of the window title. I recommend we do that instead of duplicating the text.

Other than that is works great! I love this quality of life addition!

image

**Comment by flavioislima** [comment]
> There is a duplication in the displayed text and the window title. Your sample shows the game name instead of the window title. I recommend we do that instead of duplicating the text.
> 
> Other than that it works great! I love this quality of life addition!
> 
> image

yeah, I did the change but forgot to commit and push after the screenshot. Good catch.

**Review by nyghtstalker — APPROVED** [review]
Much better. Great job!

image

**Review by BrettCleary — APPROVED** [review]
this is perfect :raised_hands: tested and it works

**Pull request merged**
